export const LOG_IN = 'LOG_IN';
export const SIGN_UP = 'SIGN_UP';
export const LOG_OUT = 'USER_LOGOUT';

export const GET_CACHED_FEEDS_ME = 'GET_CACHED_FEEDS_ME';
export const BEGIN_FETCH_ME = 'BEGIN_FETCH_ME';
export const FETCH_FEEDS_ME = 'FETCH_FEEDS_ME';
export const BEGIN_FETCH_MORE_ME = 'BEGIN_FETCH_MORE_ME';
export const FETCH_MORE_FEEDS_ME = 'FETCH_MORE_FEEDS_ME';

export const GET_CACHED_FEEDS_HOME = 'GET_CACHED_FEEDS_HOME';
export const BEGIN_FETCH_HOME = 'BEGIN_FETCH_HOME';
export const FETCH_FEEDS_HOME = 'FETCH_FEEDS_HOME';
export const BEGIN_FETCH_MORE_HOME = 'BEGIN_FETCH_MORE_HOME';
export const FETCH_MORE_FEEDS_HOME = 'FETCH_MORE_FEEDS_HOME';

export const POST_FEED = 'POST_FEED';